TELEGRAM:
  BOT_TOKEN: ""
  APP_URL: "https://linker.ru.tuna.am"
SERVER:
  HOST: ""
  PORT: "8080"
DATABASE:
  HOST: "localhost"
  PORT: "5432"
  USER: "linker"
  PASSWORD: "linker_password"
  NAME: "linker_db"